
services:
  database:
    image: postgres:15-alpine
    container_name: my_database
    restart: unless-stopped

    env_file:
      - ./BackEnd/.env
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./clean_db.sql:/docker-entrypoint-initdb.d/init.sql

  backend:
    build: ./BackEnd
    container_name: my_backend
    restart: unless-stopped
    depends_on:
      - database
    env_file:
      - ./BackEnd/.env
    ports:
      - "8080:8080"
  frontadmin:
    build: ./FrontAdmin
    container_name: front_admin
    restart: unless-stopped

    ports:
      - "5173:80"

  frontuser:
    build: ./FrontUser
    container_name: front_user
    restart: unless-stopped

    ports:
      - "5174:80"

volumes:
  postgres_data:
